export const active: string;
export const container: string;
export const icon: string;
export const lock: string;
export const lockHidden: string;
export const text: string;
export const toolbox: string;
export const view: string;
export const viewHidden: string;
