export const blur: string;
export const container: string;
export const content: string;
export const left: string;
export const list: string;
export const main: string;
export const open: string;
export const right: string;
export const search: string;
